# Generated by Django 3.0.8 on 2020-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'Confirmed'), (3, 'Refunded')], default=1),
        ),
    ]
